### ISSUE TITLE
Option patchAll not fallbacking commit to be a patch bump

### ISSUE THREAD

**Issue by chsukivra** [ietf-tools/semver-action#32]
I'm using this action on a private repo and we merged a commit with the text "WIP ... " and patchAll is set to true. Then failed on a second time and success the third time with a conventional commit pattern message.

```
Comparing against latest tag: v1.30.2
[INVALID] Skipping commit d429fa73349d7a77da72f1bc25827e0253dcfb92 as it doesn't follow conventional commit format.
[INVALID] Skipping commit 4f0ccbf3d7dad02bb047fe690198b30998ac1413 as it doesn't follow conventional commit format.
[PATCH] Commit 3e747945d76be179f07e4b8583[11](XXX) of type fix will cause a patch version bump.
``` 

I was under the impression that there wouldnt be an issue with non-conventional commit texts, that these would end up being 3 patch level increases from 1.30.2, but instead this leads to the version 1.30.3.

Have I failed to understand patchAll?

**Comment by NGPixel** [comment]
That's not how semver works. It doesn't matter how many commits there are, only 1 group (major, minor or patch) will be incremented and only by 1 **in total**. Otherwise you'd be left with plenty of gaps between versions.

As for the `patchAll` option, it applies to valid conventional commits only. So if you have a commit with a non-standard prefix (e.g. `foobar: this is a commit`), it will still count as a patch. It's however not a catch-all for commits that are invalid and don't follow the format.

If you plan on using conventional commits, you should ensure it is used at all times.
